name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install
          npm run build


      - name: Log frontend directory contents
        run: |
          echo "Logging frontend directory contents"
          ls -la ./frontend
          echo "Logging frontend/dist directory contents"
          ls -la ./frontend/dist

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Log backend directory contents
        run: |
          echo "Logging backend directory contents"
          ls -la ./backend

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.AZURE_TOKEN }}
          action: "upload"
          app_location: "./frontend" # The location of your application source code.
          api_location: "backend" # The location of your API source code.
          app_artifact_location: "dist/" # The location of your build output directory.
          app_build_command: "npm run build"
          api_build_command: "" # No build command for the backend
